- name: Install openshift prereqs
  become: yes
  yum:
    name:
    - NetworkManager
    state: present

- name: Start NetworkManager service
  become: yes
  service:
    name: NetworkManager
    state: started
    enabled: true
  notify: reboot server

# Clean up yum cache to keep disk space usage down
- name: Clean up yum cache
  become: yes
  command: yum clean all
  args:
    warn: no
